---
# tasks file for secure_ssh

- name: ensure role dependencies are installed
  package:
    name:
      - fail2ban
      - authconfig
      - policycoreutils-python
      - unzip
    state: present
  tags:
    - fail2ban
    - authconfig

- name: enable fail2ban
  systemd:
    name: fail2ban
    enabled: true
    state: started
  tags:
    - fail2ban

- name: ensure password hashing algorithm is SHA-512
  command: authconfig --passalgo=sha512 --update
  changed_when: false
  tags:
    - authconfig

- name: create sudoers.d file
  copy:
    src: 'sudoers/users_sudo'
    dest: /etc/sudoers.d/users_sudo
    owner: root
    group: root
    mode: "0440"
  tags:
    - sudoers

- name: disable requiretty in sudoers file
  lineinfile:
    path: /etc/sudoers
    regexp: '^Defaults.*requiretty'
    line: Defaults    !requiretty
    state: present
  tags:
    - sudoers

- name: install trusted-user-ca-keys.pem
  when: signed_ssh_keys is defined and signed_ssh_keys|bool
  copy:
    src: trusted-user-ca-keys.pem
    dest: /etc/ssh/trusted-user-ca-keys.pem
    owner: root
    group: root
    mode: 0644
  notify: restart sshd
  tags:
    - signed_ssh_keys

- name: Harden SSH configuration
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: '^(#)?AddressFamily'
      line: "AddressFamily {{ AddressFamily }}"
    - regexp: '^(#)?PubkeyAuthentication'
      line: "PubkeyAuthentication {{ PubkeyAuthentication }}"
    - regexp: '^ChallengeResponseAuthentication'
      line: |
        ChallengeResponseAuthentication {{ ChallengeResponseAuthentication }}
    - regexp: '^(#)?TrustedUserCAKeys'
      line: "TrustedUserCAKeys {{ TrustedUserCAKeys }}"
    - regexp: '^UsePAM'
      line: 'UsePAM yes'
    - regexp: '^(#)?Port'
      line: "Port {{ Port }}"
    - regexp: '^(#)?AuthorizedKeysFile'
      line: "AuthorizedKeysFile {{ AuthorizedKeysFile }}"
    - regexp: '^(#)?PasswordAuthentication'
      line: "PasswordAuthentication {{ PasswordAuthentication }}"
    - regexp: '^(#)?PermitEmptyPasswords'
      line: "PermitEmptyPasswords {{ PermitEmptyPasswords }}"
    - regexp: '^(#)?X11Forwarding'
      line: "X11Forwarding {{ X11Forwarding }}"
    - regexp: '^(#)?PermitRootLogin'
      line: "PermitRootLogin {{ PermitRootLogin }}"
    - regexp: '^(#)?MaxAuthTries \d'
      line: "MaxAuthTries {{ MaxAuthTries | default('10') }}"
    - regexp: '^(#)?MaxSessions'
      line: "MaxSessions {{ MaxSessions }}"
    - regexp: '^(#)?IgnoreRhosts'
      line: 'IgnoreRhosts yes'
    - regexp: '^(#)?StrictModes'
      line: 'StrictModes yes'
    - regexp: '^(#)?HostbasedAuthentication'
      line: "HostbasedAuthentication no"
    - regexp: '^(#)?PermitUserEnvironment'
      line: "PermitUserEnvironment {{ PermitUserEnvironment }}"
    - regexp: '^(#)?Ciphers'
      line: 'Ciphers aes256-ctr,aes192-ctr,aes128-ctr'
    - regexp: '^(#)?MACs'
      # yamllint disable-line rule:line-length
      line: 'MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com'
    - regexp: '^(#)?LoginGraceTime'
      line: "LoginGraceTime {{ LoginGraceTime }}"
  notify: restart sshd
  tags:
    - config

- name: ensure permissions on /etc/ssh/sshd_config are restricted
  file:
    dest: /etc/ssh/sshd_config
    state: file
    owner: root
    group: root
    mode: 0400
  notify: restart sshd
  tags:
    - config

- name: create .ssh in user skeleton
  file:
    path: /etc/skel/.ssh
    mode: 0700
    state: directory
  tags:
    - config
    - ssh_users

- name: verify if ssh config exists in user skeleton
  stat:
    path: "/etc/skel/.ssh/config"
  register: user_config
  tags:
    - config
    - ssh_users

- name: create ssh config in user skeleton
  file:
    path: /etc/skel/.ssh/config
    owner: root
    group: root
    mode: 0600
    state: "{{ 'file' if  user_config.stat.exists else 'touch'}}"
  tags:
    - config
    - ssh_users

- name: enable ForwardAgent in /etc/skel/.ssh/config file
  lineinfile:
    dest: /etc/skel/.ssh/config
    regexp: '^ForwardAgent'
    line: 'ForwardAgent yes'
    state: present
  tags:
    - config
    - ssh_users

- name: enable HashKnownHosts in /etc/ssh/ssh_config file
  lineinfile:
    dest: /etc/ssh/ssh_config
    regexp: '^HashKnownHosts'
    line: 'HashKnownHosts yes'
    state: present
  tags:
    - config
    - ssh_users

- name: create central directory for authorized_keys
  when: distribute_ssh_keys is defined and distribute_ssh_keys|bool
  file:
    dest: /etc/ssh/authorized_keys
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - ssh_users
    - non_users

- name: unlock central authorized_keys files for writing
  when: distribute_ssh_keys is defined and distribute_ssh_keys|bool
  shell: chattr -i /etc/ssh/authorized_keys/*
  changed_when: false  # it is a toggle
  ignore_errors: true
  tags:
    - ssh_users
    - non_users

- name: create ssh_groups like wheel, staff and users
  when: manage_ssh_groups is defined and manage_ssh_groups|bool
  group:
    system: true
    name: "{{ item }}"
    state: present
  with_items: "{{ ssh_groups }}"
  tags:
    - ssh_groups

- name: ensure the people in ssh_users have a user created with options
  when:
    - manage_ssh_users is defined and manage_ssh_users|bool
  user:
    name: "{{ item.username }}"
    uid: "{{ item.uid | default(omit) }}"
    group: "{{ item.group | default('users') }}"
    seuser: "{{ item.seuser | default('user_u') }}"
    comment: "{{ item.comment | default(omit) }}"
    create_home: "{{ item.create_home | default('true') }}"
    move_home: "{{ item.move_home | default(omit) }}"
    password_lock: "{{ item.password_lock | default('true') }}"
    home: "{{ item.home | default(omit) }}"
    expires: "{{ item.expires | default(omit) }}"
    generate_ssh_key: "{{ item.generate_ssh_key | default('false') }}"
    non_unique: true  # for cleaning up inconsistent uids
    shell: "{{ item.shell }}"
    state: present
    system: "{{ item.system | default(omit) }}"
  with_items:
    - "{{ ssh_users }}"
  tags:
    - ssh_users

- name: ensure the people in ssh_users have a seuser type
  when: semanage_ssh_users is defined and semanage_ssh_users|bool
  command: "semanage login -a -s {{ item.seuser | default('xguest_u') }} {{ item.username }}"
  with_items: "{{ ssh_users }}"
  tags:
    - ssh_users

- name: set the primary group for users
  when: manage_ssh_groups is defined and manage_ssh_groups|bool
  user:
    name: "{{ item.username }}"
    group: "{{ item.group | default('users') }}"
  with_items:
    - "{{ ssh_users }}"
  tags:
    - ssh_groups
    - ssh_users

- name: remove users from all groups except their primary group
  when: manage_ssh_groups is defined and manage_ssh_groups|bool
  user:
    name: "{{ item.username }}"
    group: "{{ item.group | default('users') }}"
  with_items: "{{ ssh_users }}"
  tags:
    - ssh_groups
    - ssh_users

- name: remove user private groups
  when: manage_ssh_groups is defined and manage_ssh_groups|bool
  group:
    name: "{{ item.username }}"
    state: absent
  with_items: "{{ ssh_users }}"
  tags:
    - non_users
    - ssh_groups
    - ssh_users

- name: root manages authorized keys for each user
  when:
    - distribute_ssh_keys is defined and distribute_ssh_keys|bool
    - item.group == 'wheel' or item.group == 'staff' or item.group == 'users'
  copy:
    dest: /etc/ssh/authorized_keys/{{ item.username }}
    src: "pubkeys/{{ item.username }}"
    owner: "{{ item.username }}"
    mode: 0640
  ignore_errors: true
  no_log: true
  with_items:
    - "{{ ssh_users }}"
  tags:
    - ssh_users

- name: ensure all keys of non_users are removed
  when: distribute_ssh_keys is defined and distribute_ssh_keys|bool
  file:
    dest: "/etc/ssh/authorized_keys/{{ item }}"
    state: absent
  with_items:
    - "{{ non_users }}"
  tags:
    - non_users

- name: ensure all non_users are removed
  when: manage_ssh_users is defined and manage_ssh_users|bool
  user:
    name: "{{ item }}"
    state: absent
    remove: true
    force: true
  with_items:
    - "{{ non_users }}"
  tags:
    - non_users

- name: lock central authorized_keys files for writing
  when: distribute_ssh_keys is defined and distribute_ssh_keys|bool
  shell: chattr +i /etc/ssh/authorized_keys/*
  changed_when: false  # it is a toggle
  ignore_errors: true
  tags:
    - ssh_users
    - non_users

- name: ensure users have no authorized_keys in their homedir
  when: distribute_ssh_keys is defined and distribute_ssh_keys|bool
  file:
    state: absent
    path: "{{ item }}/.ssh/authorized_keys"
  with_items:
    - "{{ ssh_users }}"
  tags:
    - ssh_users

## TODO Hashicorp Vault
- name: download vault-ssh-helper from the internet
  when: hashicorp_vault_ssh is defined and hashicorp_vault_ssh|bool
  delegate_to: localhost
  become: false
  get_url:
    url: "{{ vault_helper_url }}"
    sha256sum: "{{ vault_helper_sha256sum }}"
    dest: "/tmp/{{ vault_helper_zip }}"
    timeout: 30
  register: task_result
  until: task_result is success
  retries: 3
  delay: 10

- name: unpack vault-ssh-helper
  when: hashicorp_vault_ssh is defined and hashicorp_vault_ssh|bool
  unarchive:
    src: "/tmp/{{ vault_helper_zip }}"
    dest: "/usr/bin"
    creates: "/usr/bin/vault-ssh-helper"

- name: create directory for vault-ssh-helper
  when: hashicorp_vault_ssh is defined and hashicorp_vault_ssh|bool
  file:
    path: "/etc/vault-ssh-helper.d"
    state: directory

- name: copy vault-ssh-helper configuration file
  when: hashicorp_vault_ssh is defined and hashicorp_vault_ssh|bool
  template:
    src: config.hcl
    dest: /etc/vault-ssh-helper.d/config.hcl

- name: Comment common-auth mechanism
  when: hashicorp_vault_ssh is defined and hashicorp_vault_ssh|bool
  lineinfile:
    firstmatch: true
    path: "/etc/pam.d/sshd"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - {regexp: '^auth       substack     password-auth', line: '#auth       substack     password-auth'}
    - {regexp: '^password   include      password-auth', line: '#password   include      password-auth'}

- name: Insert the vault-ssh-helper configuration for ssh auth
  when: hashicorp_vault_ssh is defined and hashicorp_vault_ssh|bool
  blockinfile:
    path: "/etc/pam.d/sshd"
    block: |
      auth requisite pam_exec.so quiet expose_authtok log=/tmp/vaultssh.log /usr/bin/vault-ssh-helper -config=/etc/vault-ssh-helper.d/config.hcl
      auth optional pam_unix.so not_set_pass use_first_pass nodelay
    insertbefore: "auth       include      postlogin"
    state: present
