---
# handlers file for secure_ssh

- name: restart sshd
  debug:
    msg: "checking /etc/ssh/sshd_config first"
  changed_when: true
  notify:
    - check sshd configuration
    - restart sshd - after config check

- name: check sshd configuration
  command: '/usr/sbin/sshd -t'
  register: sshd_config
  changed_when: "sshd_config.rc != 0"

- name: restart sshd - after config check
  service:
    name: sshd
    state: restarted

- name: restart firewalld
  systemd:
    name: firewalld
    state: restarted
    daemon_reload: true

- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted
    daemon_reload: true
