---
- name: Cleanup
  hosts: all
  become: true
  gather_facts: false

  tasks:

    - name: ensure role dependencies are installed
      package:
        name:
          - e2fsprogs  # for chattr
        state: present
      ignore_errors: true

    - name: reset immutable bits
      shell: chattr -i /etc/ssh/authorized_keys/*
      changed_when: true
      ignore_errors: true
