---
dependency:
  name: galaxy
  requirements_file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
  ssh_connection_options:
    - '-o IdentityFile=~/.vagrant.d/insecure_private_key'
lint:
  name: yamllint
platforms:
  - name: centos
    box: centos/7
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
      stdout_callback: yaml
  lint:
    name: ansible-lint
verifier:
  name: goss
  lint:
    name: yamllint
