---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: base-ssh-centos7
    image: centos:7
    command: /sbin/init
    capabilities:
      - LINUX_IMMUTABLE
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#  - name: base-ssh-centos8
#    image: centos:8
#    command: /sbin/init
#    capabilities:
#      - LINUX_IMMUTABLE
#    tmpfs:
#      - /run
#      - /tmp
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible
