---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: base-ssh-centos7
    image: centos:7.9.2009
    command: /sbin/init
    capabilities:
      - LINUX_IMMUTABLE
      - NET_BIND_SERVICE
    published_ports:
      - 127.0.0.1:2222:22
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#  - name: base-ssh-centos8
#    image: centos:8
#    command: /sbin/init
#    capabilities:
#      - LINUX_IMMUTABLE
#    tmpfs:
#      - /run
#      - /tmp
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - lint
    - syntax
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
