---
- name: Converge
  hosts: all
  become: true
  vars:
    # set ChallengeResponseAuthentication yes for use with Hashicorp Vault
    ChallengeResponseAuthentication: 'yes'
    hashicorp_vault_ssh: true

    signed_ssh_keys: false
    # Please read the tasks before enabling
    distribute_ssh_keys: true
    # Change from user private groups to 'ssh_groups:'
    manage_ssh_groups: true
    # Confine users to seuser classes not idempotent
    semanage_ssh_users: false
    manage_ssh_users: true
    ssh_users:
      - username: vagrant
        shell: /bin/bash
        group: wheel
        seuser: unconfined_u
      - username: admin
        shell: /bin/bash
        group: wheel
        seuser: staff_u
      - username: download
        shell: /sbin/nologin
        group: chroot
        seuser: guest_u
      - username: kiosk
        shell: /bin/bash
        group: games
        seuser: xguest_u

  roles:
    - role: dockpack.base_epel
    - role: secure_ssh
