---
- name: Converge
  hosts: all
  become: true
  vars:
    signed_ssh_keys: true
    # Please read the tasks before enabling
    distribute_ssh_keys: true
    # Change from user private groups to 'ssh_groups:'
    manage_ssh_groups: true
    # Confine users to seuser classes
    # adds all in 'ssh_users:' removes all 'non_users:'
    manage_ssh_users: true
    ssh_users:
      - username: guest
        shell: /bin/bash
        group: games
        seuser: guest_u
      - username: kiosk
        shell: /bin/bash
        group: games
        seuser: xguest_u

  roles:
    - role: base_epel
    - role: secure_ssh
