---
- name: Converge
  hosts: all
  become: true
  vars:
    signed_ssh_keys: true
    PasswordAuthentication: 'yes'
    # Please read the tasks before enabling
    distribute_ssh_keys: true
    # Change from user private groups to 'ssh_groups:'
    manage_ssh_groups: true
    # Confine users to seuser classes
    manage_ssh_users: true
    ssh_users:
      - username: vagrant
        shell: /bin/bash
        group: wheel
        seuser: unconfined_u
      - username: admin
        shell: /bin/bash
        group: users
        seuser: staff_u
      - username: guest
        shell: /bin/bash
        group: games
        seuser: guest_u
      - username: kiosk
        shell: /bin/bash
        group: games
        seuser: xguest_u

  roles:
    - role: base_epel
    - role: secure_ssh
